services:
  - type: web
    name: ieee-gehu-api
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    plan: free
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: PORT
        value: "5000"
      - key: MONGO_URI
        value: "pending"
      - key: FRONTEND_URL
        value: https://ieee-web-seven.vercel.app
