name: 🐛 Bug Report
description: Report a bug to help us improve.
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: How to reproduce?
      description: Provide steps to reproduce the behavior.
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: OS, Browser, Node version, etc.
  - type: checkboxes
    id: terms
    attributes:
      label: Bug confirmation
      options:
        - label: I confirm that this is a bug and not a question.
          required: true
